"""Diagnostic: Try WHO=0 scenario commands and listen for bus responses.

The MH200 scenario programmer may respond to WHO=0 (scenario recall) rather
than WHO=15 (CEN). This test also opens an EVENT session to capture any bus
traffic generated by a successful scenario trigger.
"""

import asyncio
import sys


GATEWAY_IP = "192.168.1.40"
GATEWAY_PORT = 20000
PASSWORD = "12345"


def _get_own_password(password: str, nonce: str) -> int:
    start = True
    num1 = 0
    num2 = 0
    password_int = int(password)
    for character in nonce:
        if character != "0":
            if start:
                num2 = password_int
            start = False
        if character == "1":
            num1 = (num2 & 0xFFFFFF80) >> 7
            num2 = num2 << 25
        elif character == "2":
            num1 = (num2 & 0xFFFFFFF0) >> 4
            num2 = num2 << 28
        elif character == "3":
            num1 = (num2 & 0xFFFFFFF8) >> 3
            num2 = num2 << 29
        elif character == "4":
            num1 = num2 << 1
            num2 = num2 >> 31
        elif character == "5":
            num1 = num2 << 5
            num2 = num2 >> 27
        elif character == "6":
            num1 = num2 << 12
            num2 = num2 >> 20
        elif character == "7":
            num1 = (
                num2 & 0x0000FF00
                | ((num2 & 0x000000FF) << 24)
                | ((num2 & 0x00FF0000) >> 16)
            )
            num2 = (num2 & 0xFF000000) >> 8
        elif character == "8":
            num1 = (num2 & 0x0000FFFF) << 16 | (num2 >> 24)
            num2 = (num2 & 0x00FF0000) >> 8
        elif character == "9":
            num1 = ~num2
        else:
            num1 = num2
        num1 &= 0xFFFFFFFF
        num2 &= 0xFFFFFFFF
        if character not in "09":
            num1 |= num2
        num2 = num1
    return num1


async def open_session(session_type: str):
    """session_type: '0' for COMMAND, '1' for EVENT"""
    reader, writer = await asyncio.open_connection(GATEWAY_IP, GATEWAY_PORT)
    await asyncio.wait_for(reader.readuntil(b"##"), timeout=5)
    writer.write(f"*99*{session_type}##".encode())
    await writer.drain()
    resp = await asyncio.wait_for(reader.readuntil(b"##"), timeout=5)
    resp_str = resp.decode().strip()
    if resp_str == "*#*1##":
        return reader, writer
    nonce = resp_str.replace("*#", "").replace("##", "")
    hashed = _get_own_password(PASSWORD, nonce)
    writer.write(f"*#{hashed}##".encode())
    await writer.drain()
    ack = await asyncio.wait_for(reader.readuntil(b"##"), timeout=5)
    if "*#*1" not in ack.decode():
        print(f"AUTH FAILED for session type {session_type}")
        sys.exit(1)
    return reader, writer


async def send(writer, reader, cmd: str):
    print(f"  >> {cmd}")
    writer.write(cmd.encode("ascii"))
    await writer.drain()
    try:
        resp = await asyncio.wait_for(reader.readuntil(b"##"), timeout=3)
        r = resp.decode().strip()
        result = "ACK" if "*#*1" in r else ("NACK" if "*#*0" in r else r)
        print(f"  << {result}")
        return result
    except asyncio.TimeoutError:
        print("  << TIMEOUT (no ACK/NACK)")
        return "TIMEOUT"


async def listen_events(reader, duration=5):
    """Listen for bus events for 'duration' seconds."""
    print(f"  [Listening for bus events for {duration}s...]")
    end = asyncio.get_event_loop().time() + duration
    events = []
    while asyncio.get_event_loop().time() < end:
        try:
            remaining = end - asyncio.get_event_loop().time()
            data = await asyncio.wait_for(
                reader.readuntil(b"##"), timeout=max(0.1, remaining)
            )
            msg = data.decode().strip()
            print(f"  BUS EVENT: {msg}")
            events.append(msg)
        except asyncio.TimeoutError:
            continue
        except Exception:
            break
    if not events:
        print("  (no events captured)")
    return events


async def main():
    print("=== WHO=0 Scenario + Bus Monitor Diagnostic ===\n")

    # Open EVENT session first
    print("[1] Opening EVENT session (bus monitor)...")
    evt_reader, evt_writer = await open_session("1")
    print("  Event session open.\n")

    # Open COMMAND session
    print("[2] Opening COMMAND session...")
    cmd_reader, cmd_writer = await open_session("0")
    print("  Command session open.\n")

    # Test: WHO=0 scenario commands with various WHAT/WHERE combos
    test_commands = [
        ("WHO=0 WHAT=1 WHERE=21", "*0*1*21##"),
        ("WHO=0 WHAT=2 WHERE=21", "*0*2*21##"),
        ("WHO=0 WHAT=1 WHERE=1",  "*0*1*1##"),
        ("WHO=0 WHAT=1 WHERE=0",  "*0*1*0##"),
        # Also try the direct source routing commands that the wall panel uses
        ("WHO=16 Source1 ON (101)", "*16*3*101##"),
        ("WHO=16 Route 1->1 (121)", "*16*3*121##"),
    ]

    for label, cmd in test_commands:
        print(f"\n--- {label} ---")
        result = await send(cmd_writer, cmd_reader, cmd)

        # Listen for any bus events this might have triggered
        await listen_events(evt_reader, duration=2)

    # Cleanup
    print("\n[3] Closing connections...")
    cmd_writer.close()
    evt_writer.close()
    print("\n=== DONE ===")


if __name__ == "__main__":
    asyncio.run(main())
